#include <stdlib.h>

/* This is a two part test.
 *
 * Part 1 runs without a callstack input file and generates an output
 * callstack file.
 *
 * Part 2 uses the callstack file generated by part 1 to test
 * allocation successes.
 *
 * The point of having the two tests is that the output callstack file may have
 * different addresses on different architectures/builds, so it must be
 * generated on the fly.
 */

void f_a(int level)
{
   int* p;

   p = malloc(10);
   if (level > 0) {
      f_a(level-1);
   }

   if (p) free(p);
}


int main(int argc, char* argv[])
{
   f_a(10);

   return 0;
}
