Heap memory failure
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: alloc_func (alloc_toggle_1.c:7)
   by 0x........: middle (alloc_toggle_1.c:16)
   by 0x........: testing (alloc_toggle_1.c:22)
   by 0x........: main (alloc_toggle_1.c:34)
 Failgrind: 0 call stacks loaded from file
            0 allocations succeeded
            1 allocations failed
            1 new allocation callstacks found
            1 syscalls succeeded
            0 syscalls failed
            0 new syscall callstacks found
