Heap memory failure
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (alloc_thresh_high_low_invert1.c:8)
Heap memory failure
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (alloc_thresh_high_low_invert1.c:14)
Heap memory failure
   at 0x........: malloc (vg_replace_malloc.c:...)
   by 0x........: main (alloc_thresh_high_low_invert1.c:20)
 Failgrind: 0 call stacks loaded from file
            0 allocations succeeded
            3 allocations failed
            3 new allocation callstacks found
            1 syscalls succeeded
            0 syscalls failed
            0 new syscall callstacks found
