   at 0x........: open (open64.c:...)
   by 0x........: syscall_func (syscall_toggle_1.c:12)
   by 0x........: middle (syscall_toggle_1.c:22)
   by 0x........: testing (syscall_toggle_1.c:28)
   by 0x........: main (syscall_toggle_1.c:40)
 Failgrind: 0 call stacks loaded from file
            0 allocations succeeded
            0 allocations failed
            0 new allocation callstacks found
            11 syscalls succeeded
            1 syscalls failed
            1 new syscall callstacks found
